Repository MirahezeBots/MirahezeBots, pull requests merged in 2020-06, with the labels that each got.

#189 Remvoing urls hack
  modules/urls.py
Labels: fix

#196 Remove join hack and rename to joinall.py
  modules/join.py
  modules/joinall.py
Labels: enhancement

#199 Release Version 7
  .travis.yml
  RELEASE-NOTES-V7
  SECURITY.md
  modules/mh_phab.py
  modules/models.py
  modules/responses.py
  modules/shortlinks.py
  modules/utils/__init__.py
  modules/utils/phabricator.py
  tests/__init__.py
  tests/cassettes/phabricator_find_tasks.yaml
  tests/cassettes/phabricator_get_task.yaml
  tests/test_phabricator.py
Labels: bug, enhancement

#203 Re-deploy version7
  .travis.yml
  RELEASE-NOTES-V7
  SECURITY.md
  modules/mh_phab.py
  modules/models.py
  modules/responses.py
  modules/shortlinks.py
  modules/utils/__init__.py
  modules/utils/phabricator.py
  tests/__init__.py
  tests/cassettes/phabricator_find_tasks.yaml
  tests/cassettes/phabricator_get_task.yaml
  tests/test_phabricator.py
Labels: enhancement
